import {
	IconAirTrafficControl,
	IconAlertTriangle,
	IconArrowRight,
	IconBrandGithub,
	IconBrandTwitter,
	IconBuildingFactory2,
	IconCheck,
	IconChevronLeft,
	IconChevronRight,
	IconCommand,
	IconCreditCard,
	IconDeviceLaptop,
	IconDotsVertical,
	IconFile,
	IconFileText,
	IconHelpCircle,
	IconLayoutDashboard,
	IconLayoutKanban,
	IconLoader2,
	IconLogin,
	IconMessage2,
	IconMoon,
	IconPhoto,
	IconPizza,
	IconPlus,
	IconProps,
	IconSettings,
	IconShoppingBag,
	IconSun,
	IconTrash,
	IconUser,
	IconUserCircle,
	IconUserEdit,
	IconUserX,
	IconX
} from '@tabler/icons-react'
import { LucideClipboardCheck } from 'lucide-react'

export type Icon = React.ComponentType<IconProps>

export const Icons = {
	dashboard: IconLayoutDashboard,
	logo: IconCommand,
	login: IconLogin,
	close: IconX,
	order: LucideClipboardCheck,
	manufacturer: IconBuildingFactory2,
	product: IconShoppingBag,
	spinner: IconLoader2,
	kanban: IconLayoutKanban,
	chevronLeft: IconChevronLeft,
	chat: IconMessage2,
	chevronRight: IconChevronRight,
	category: IconAirTrafficControl,
	trash: IconTrash,
	employee: IconUserX,
	post: IconFileText,
	page: IconFile,
	userPen: IconUserEdit,
	user2: IconUserCircle,
	media: IconPhoto,
	settings: IconSettings,
	billing: IconCreditCard,
	ellipsis: IconDotsVertical,
	add: IconPlus,
	warning: IconAlertTriangle,
	user: IconUser,
	arrowRight: IconArrowRight,
	help: IconHelpCircle,
	pizza: IconPizza,
	sun: IconSun,
	moon: IconMoon,
	laptop: IconDeviceLaptop,
	github: IconBrandGithub,
	twitter: IconBrandTwitter,
	check: IconCheck
}
